### ISSUE TITLE
Issue when installed as a service.

### ISSUE THREAD

**Issue by FlorianWendelborn** [jwalgran/playback#1]
## Story

I want(ed) to use this module to control my iTunes instance for home automation purposes, which is done by a windows service on my main pc (and some other stuff on other ones that doesn't matter for this issue).
## Issue

After installing my node script containing [playback](https://github.com/jwalgran/playback) as a windows service via [node-windows](https://github.com/coreybutler/node-windows) it didn't work anymore. I could not control iTunes as I did while testing it running as a normal task. It seems to **spawn a complete instance of iTunes** in the mentioned service and can't even terminate the calls to cscript.exe as it proceeds to **spawn over 500 processes** (then I stopped it), averaging at about 5 per second. This leads to the module not working anymore and being unable to start iTunes.
## Screenshots

![image](https://cloud.githubusercontent.com/assets/1133858/5875259/86939ca0-a30b-11e4-8ab1-10dcb1002ca4.png)
![image](https://cloud.githubusercontent.com/assets/1133858/5875416/3031ed42-a30d-11e4-9219-8bc1c30afea3.png)
## Sample-Code to reproduce
- only tested on this particular system:
  - highly custom configured
  - Windows 7 Ultimate 64-Bit
  - node v0.11.13
  - npm v1.4.9
  - playback v0.1.1
  - node-windows v0.1.7
### install.js

```
var Service = require('node-windows').Service;

var svc = new Service({
    name: 'playback',
    description: 'testing service',
    script: __dirname + '/playback.test.js'
});

svc.on('install',function(){
    svc.start();
    console.log('Installation complete.');
});

svc.install();
```
### uninstall.js

```
var Service = require('node-windows').Service;

var svc = new Service({
    name: 'playback',
    description: 'testing service',
    script: __dirname + '/playback.test.js'
});

svc.on('uninstall',function(){
    console.log('Uninstall complete.');
});

svc.uninstall();
```
### playback.test.js

```
var itunes = require('playback');
itunes.on('playing', function(data){ console.dir(data);} );
itunes.on('paused', function(data){ console.log('paused');} );
itunes.play();
```

**Comment by jwalgran** [comment]
Sorry you ran into problem using the module in a Windows service. I really appreciate the thorough bug report.

This may be a problem with the Windows service running under the NETWORK SERVICE account, which may not be able to launch a GUI application, like iTunes. Could you try updating the service to run as your account via the Log On tab of the service properties to see if that corrects the issue?

![screen shot 2015-01-23 at 9 26 36 am](https://cloud.githubusercontent.com/assets/17363/5878181/1ed2ecde-a2e2-11e4-995b-02fe5097f4ff.png)

**Comment by FlorianWendelborn** [comment]
Unfortunately that did not work for me, because I'm getting login errors (might be because my account doesn't have a password as I already use TrueCrypt. I solved it (at least for my personal purposes) by using [hstart](http://www.ntwind.com/software/hstart.html) combined with the autostart/startup-folder and a `.bat` file.
