### ISSUE TITLE
Abnormally high CPU usage on Mac OS X 10.11.2

### ISSUE THREAD

**Issue by callum** [jwalgran/playback#7]
I noticed that my fan was getting noisy immediately after starting my app. It looks like launchservicesd comes under a lot of load. The CPU is at a constant 90% whilst the app is running

![screen shot 2016-02-20 at 16 46 41](https://cloud.githubusercontent.com/assets/1245446/13197972/77ffca14-d7f4-11e5-80e2-47bc83da6a39.png)

I did my best to debug it using [devtool](https://github.com/Jam3/devtool) but all it could tell me was that `spawn` was using up the most resource - perhaps because it's polling so often? Or is it likely to be an issue on the AppleScript side?

I tested with the following code:

``` js
const playback = require('playback')
playback.on('playing', console.log.bind(console))
```

I know there's not much to go on, but hope you're able to help. Thanks

**Comment by FlorianWendelborn** [comment]
When using this package I had similar issues. It spawned some thousand threads which made my PC hang after ~5minutes.
